<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Kawsay.Application\Application.csproj" />
      <ProjectReference Include="..\Kawsay.Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.25.3" />
      <PackageReference Include="Grpc.Net.Client" Version="2.61.0" />
      <PackageReference Include="Grpc.Tools" Version="2.62.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Protobuf Include="Protos\problem_definition.proto" GrpcServices="Client" />
      <Protobuf Include="Protos\solution.proto" GrpcServices="Client" />
    </ItemGroup>

</Project>
